### ISSUE TITLE
make sanity-check act like a nagios plug-in

### ISSUE THREAD

**Issue by mschreie** [SatelliteQE/satellite-sanity#1]
might be smart if the sanity check could be used as nagios plug-in.
Please refere to 
  http://www.yourownlinux.com/2014/06/how-to-create-nagios-plugin-using-bash-script.html

you would need to assure 
a) shell convenience wrappers for `satellite-sanity -t generic,Satellite_5` and `satellite-sanity -t generic,Satellite_6`.
b) correct exit codes: 
exit 0 - Whenever the status of the output of the executed script is "OK", Nagios Server would highlight the check with Green color.
exit 1 - Whenever the status of the output of the executed script is "WARNING", Nagios Server would highlight the check with Yellow color.
exit 2 - Whenever the status of the output of the executed script is "CRITICAL", Nagios Server would highlight the check with Red color.
exit 3 - Whenever the status of the output of the executed script is "UNKNOWN", Nagios Server would highlight the check with Grey color. 

exit 3 mostly, when the script could not run through due to config/syntax/... errors, which an admin needs to fix.

4) short output on STD-OUT according to the following syntax:
[STATUS]- [INFORMATION TO BE DISPLAYED ON NAGIOS SERVER CONSOLE] | [INFORMATION TO BE DISPLAYED GRAPHICALLY]

... maybe newer nagios might like more advanced output. Please check out:
https://nagios-plugins.org/doc/guidelines.html

**Comment by jhutar** [comment]
Thank you very much for this suggestion.
